### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by keeganquinn**
I needed the dependencies in a script, so I took them from here. This is that script integrated back.

### CODE REVIEW

**Comment by bnfinet** [comment]
glad to see some love of the docker based build

let's review this patch together at the next hack night

**Comment by RussellSenior** [comment]
@bnfinet can you look at this and merge-or-give feedback.  i don't use this, so I'm not the person to review.

**Comment by keeganquinn** [comment]
To be candid, I doubt anyone uses this, including me; I'm just getting familiar with build stuff again and this was a stepping stone along the path. With that said, I'm fairly confident that these changes are safe to apply - this is just a little pushback against bit rot. LEDE instead of OpenWrt, etc. Detailed review would always be welcome.

Thanks!

**Comment by keeganquinn** [comment]
Probably worth mentioning, since this is actually a thread: this PR no longer does what the top comment described in 2015. Dockerfile once again has all the system setup stuff, as it did in Ben's original work. So, while it's still a bit of a refactor, this merge request is now more of a refresh.

**Comment by keeganquinn** [comment]
Just threw in an MIT license too, since that's a nice thing to formalize, but mentioning it here to be clear that I'm not trying to force this particular license or copyright statement - this is Ben's work. I'll remove this posthaste if there are any concerns.

**Pull request merged**
